import os
from flask import Flask, request, jsonify
from datetime import datetime
import freqtrade

app = Flask(__name__)

PREDICTION_FILE = "/app/pred.txt"

@app.route('/computation', methods=['POST'])
def computation():
    """
    Reads the latest prediction result from the pred.txt file
    generated by the running freqtrade bot.
    """
    try:
        if not os.path.exists(PREDICTION_FILE):
            return jsonify({"error": "Prediction file not found. The bot may still be initializing."}), 404

        with open(PREDICTION_FILE, "r") as f:
            lines = f.read().splitlines()

        # Parse the file content into a structured JSON object
        if len(lines) < 4:
            return jsonify({"error": "Prediction file is incomplete."}), 500

        timestamp = lines[0]
        predictions = {}
        for line in lines[1:]:
            parts = line.split(': ')
            if len(parts) == 2:
                key = parts[0].strip()
                value = float(parts[1].strip())
                predictions[key] = value

        return jsonify({"timestamp": timestamp, "predictions": predictions})

    except Exception as e:
        return jsonify({"error": f"An error occurred: {str(e)}"}), 500

if __name__ == '__main__':
    port = int(os.environ.get("APP_PORT", 8084))
    app.run(host='0.0.0.0', port=port)